admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

formation:
    resource: "@FormationBundle/Controller/"
    type:     annotation
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation


