<?php

namespace Formation\FormationBundle\Repository;

/**
 * EtatCandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatCandidatureRepository extends \Doctrine\ORM\EntityRepository
{
}
