<?php

namespace Formation\FormationBundle\Repository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository
{
	public function findSortedByName(){
		return $this->createQueryBuilder('p')
		->select('p')
		->orderBy('p.nom', 'ASC')
		->getQuery()
		->getResult();


	}
}
